### ISSUE TITLE
Figma UI Design

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-frontend#1]
# 🔽 Project's front-end wireframes
>  [Figma Link](https://www.figma.com/files/project/33669874/Team-project?fuid=993533846897764670)

## Project UI
- [x] Login UI (#2)
- [x] Register UI (#3)
- [x] Card UI (#4)
- [x] Logo (#5)
- [x] User Profile UI (#6)
- [x] User Profile Editing UI (#7)
- [x] NavBar(#17)
- [x] Friend Profile Page UI(#13)
- [x] Ranking Page(#14)
- [x] Add Card Page(#15)
- [x] Edit Card Page(#16)

**Comment by hatoriMain** [comment]
We have decided on the UI design in a rectangle style.
